#pragma once

namespace ui {
    enum class default_keys : uint32_t {
        key = 0,
        total
    };

    inline static std::map<default_keys, const char*> default_key_icon_path_map = {
        { default_keys::key, R"(.\Data\SKSE\Plugins\resources\key\Blank_Black_Normal.png)" }
    };

    //scancodes (a selection)
    enum class key_values : uint32_t {
        escape = 1,
        one = 2,
        two = 3,
        three = 4,
        four = 5,
        five = 6,
        six = 7,
        seven = 8,
        eight = 9,
        nine = 10,
        zero = 11,
        minus = 12,
        //equals = 13,
        back = 14,
        tab = 15,
        q = 16,
        w = 17,
        e = 18,
        r = 19,
        t = 20,
        y = 21,
        u = 22,
        i = 23,
        o = 24,
        p = 25,
        lbracket = 26,
        rbracket = 27,
        RETURN = 28,
        lcontrol = 29,
        a = 30,
        s = 31,
        d = 32,
        f = 33,
        g = 34,
        h = 35,
        j = 36,
        k = 37,
        l = 38,
        semicolon = 39,
        lshift = 42,
        //backslash = 43,
        z = 44,
        x = 45,
        c = 46,
        v = 47,
        b = 48,
        n = 49,
        m = 50,
        //comma = 51,
        //period = 52,
        //slash = 53,
        rshift = 54,
        multiply = 55,
        lmenu = 56,
        space = 57,
        capital = 58,
        f1 = 59,
        f2 = 60,
        f3 = 61,
        f4 = 62,
        f5 = 63,
        f6 = 64,
        f7 = 65,
        f8 = 66,
        f9 = 67,
        f10 = 68,
        numlock = 69,
        numpad7 = 71,
        numpad8 = 72,
        numpad9 = 73,
        subtract = 74,
        numpad4 = 75,
        numpad5 = 76,
        numpad6 = 77,
        add = 78,
        numpad1 = 79,
        numpad2 = 80,
        numpad3 = 81,
        numpad0 = 82,
        f11 = 87,
        f12 = 88,
        numpadenter = 156,
        rcontrol = 157,
        rmenu = 184,
        home = 199,
        up = 200,
        prior = 201,
        left = 203,
        right = 204,
        end = 207,
        down = 208,
        next = 209,
        insert = 210,
        delete_key = 211,
        lwin = 219,
        rwin = 220,
        left_button = 256,
        right_button = 257,
        middle_button = 258,
        mouse_button_4 = 259,
        mouse_button_5 = 260,
        mouse_button_6 = 261,
        mouse_button_7 = 262,
        total
    };

    inline static std::map<key_values, const char*> key_icon_path_map = {
        { key_values::zero, R"(.\Data\SKSE\Plugins\resources\key\0_Key_Dark.png)" },
        { key_values::one, R"(.\Data\SKSE\Plugins\resources\key\1_Key_Dark.png)" },
        { key_values::two, R"(.\Data\SKSE\Plugins\resources\key\2_Key_Dark.png)" },
        { key_values::three, R"(.\Data\SKSE\Plugins\resources\key\3_Key_Dark.png)" },
        { key_values::four, R"(.\Data\SKSE\Plugins\resources\key\4_Key_Dark.png)" },
        { key_values::five, R"(.\Data\SKSE\Plugins\resources\key\5_Key_Dark.png)" },
        { key_values::six, R"(.\Data\SKSE\Plugins\resources\key\6_Key_Dark.png)" },
        { key_values::seven, R"(.\Data\SKSE\Plugins\resources\key\7_Key_Dark.png)" },
        { key_values::eight, R"(.\Data\SKSE\Plugins\resources\key\8_Key_Dark.png)" },
        { key_values::nine, R"(.\Data\SKSE\Plugins\resources\key\9_Key_Dark.png)" },
        { key_values::numpad0, R"(.\Data\SKSE\Plugins\resources\key\0_Key_Dark.png)" },
        { key_values::numpad1, R"(.\Data\SKSE\Plugins\resources\key\1_Key_Dark.png)" },
        { key_values::numpad2, R"(.\Data\SKSE\Plugins\resources\key\2_Key_Dark.png)" },
        { key_values::numpad3, R"(.\Data\SKSE\Plugins\resources\key\3_Key_Dark.png)" },
        { key_values::numpad4, R"(.\Data\SKSE\Plugins\resources\key\4_Key_Dark.png)" },
        { key_values::numpad5, R"(.\Data\SKSE\Plugins\resources\key\5_Key_Dark.png)" },
        { key_values::numpad6, R"(.\Data\SKSE\Plugins\resources\key\6_Key_Dark.png)" },
        { key_values::numpad7, R"(.\Data\SKSE\Plugins\resources\key\7_Key_Dark.png)" },
        { key_values::numpad8, R"(.\Data\SKSE\Plugins\resources\key\8_Key_Dark.png)" },
        { key_values::numpad9, R"(.\Data\SKSE\Plugins\resources\key\9_Key_Dark.png)" },
        { key_values::f10, R"(.\Data\SKSE\Plugins\resources\key\F10_Key_Dark.png)" },
        { key_values::f11, R"(.\Data\SKSE\Plugins\resources\key\F11_Key_Dark.png)" },
        { key_values::f12, R"(.\Data\SKSE\Plugins\resources\key\F12_Key_Dark.png)" },
        { key_values::a, R"(.\Data\SKSE\Plugins\resources\key\A_Key_Dark.png)" },
        { key_values::lmenu, R"(.\Data\SKSE\Plugins\resources\key\Alt_Key_Dark.png)" },
        { key_values::rmenu, R"(.\Data\SKSE\Plugins\resources\key\Alt_Key_Dark.png)" },
        { key_values::down, R"(.\Data\SKSE\Plugins\resources\key\Arrow_Down_Key_Dark.png)" },
        { key_values::left, R"(.\Data\SKSE\Plugins\resources\key\Arrow_Left_Key_Dark.png)" },
        { key_values::right, R"(.\Data\SKSE\Plugins\resources\key\Arrow_Right_Key_Dark.png)" },
        { key_values::up, R"(.\Data\SKSE\Plugins\resources\key\Arrow_Up_Key_Dark.png)" },
        { key_values::multiply, R"(.\Data\SKSE\Plugins\resources\key\Asterisk_Key_Dark.png)" },
        { key_values::b, R"(.\Data\SKSE\Plugins\resources\key\B_Key_Dark.png)" },
        { key_values::back, R"(.\Data\SKSE\Plugins\resources\key\Backspace_Key_Dark.png)" },
        { key_values::lbracket, R"(.\Data\SKSE\Plugins\resources\key\Bracket_Left_Key_Dark.png)" },
        { key_values::rbracket, R"(.\Data\SKSE\Plugins\resources\key\Bracket_Right_Key_Dark.png)" },
        { key_values::c, R"(.\Data\SKSE\Plugins\resources\key\C_Key_Dark.png)" },
        { key_values::capital, R"(.\Data\SKSE\Plugins\resources\key\Caps_Lock_Key_Dark.png)" },
        { key_values::lcontrol, R"(.\Data\SKSE\Plugins\resources\key\Ctrl_Key_Dark.png)" },
        { key_values::rcontrol, R"(.\Data\SKSE\Plugins\resources\key\Ctrl_Key_Dark.png)" },
        { key_values::d, R"(.\Data\SKSE\Plugins\resources\key\D_Key_Dark.png)" },
        { key_values::delete_key, R"(.\Data\SKSE\Plugins\resources\key\Del_Key_Dark.png)" },
        { key_values::e, R"(.\Data\SKSE\Plugins\resources\key\E_Key_Dark.png)" },
        { key_values::end, R"(.\Data\SKSE\Plugins\resources\key\End_Key_Dark.png)" },
        { key_values::RETURN, R"(.\Data\SKSE\Plugins\resources\key\Enter_Key_Dark.png)" },
        { key_values::numpadenter, R"(.\Data\SKSE\Plugins\resources\key\Enter_Tall_Key_Dark.png)" },
        { key_values::escape, R"(.\Data\SKSE\Plugins\resources\key\Esc_Key_Dark.png)" },
        { key_values::f, R"(.\Data\SKSE\Plugins\resources\key\F_Key_Dark.png)" },
        { key_values::f1, R"(.\Data\SKSE\Plugins\resources\key\F1_Key_Dark.png)" },
        { key_values::f2, R"(.\Data\SKSE\Plugins\resources\key\F2_Key_Dark.png)" },
        { key_values::f3, R"(.\Data\SKSE\Plugins\resources\key\F3_Key_Dark.png)" },
        { key_values::f4, R"(.\Data\SKSE\Plugins\resources\key\F4_Key_Dark.png)" },
        { key_values::f5, R"(.\Data\SKSE\Plugins\resources\key\F5_Key_Dark.png)" },
        { key_values::f6, R"(.\Data\SKSE\Plugins\resources\key\F6_Key_Dark.png)" },
        { key_values::f7, R"(.\Data\SKSE\Plugins\resources\key\F7_Key_Dark.png)" },
        { key_values::f8, R"(.\Data\SKSE\Plugins\resources\key\F8_Key_Dark.png)" },
        { key_values::f9, R"(.\Data\SKSE\Plugins\resources\key\F9_Key_Dark.png)" },
        { key_values::g, R"(.\Data\SKSE\Plugins\resources\key\G_Key_Dark.png)" },
        { key_values::h, R"(.\Data\SKSE\Plugins\resources\key\H_Key_Dark.png)" },
        { key_values::home, R"(.\Data\SKSE\Plugins\resources\key\Home_Key_Dark.png)" },
        { key_values::i, R"(.\Data\SKSE\Plugins\resources\key\I_Key_Dark.png)" },
        { key_values::insert, R"(.\Data\SKSE\Plugins\resources\key\Insert_Key_Dark.png)" },
        { key_values::j, R"(.\Data\SKSE\Plugins\resources\key\J_Key_Dark.png)" },
        { key_values::k, R"(.\Data\SKSE\Plugins\resources\key\K_Key_Dark.png)" },
        { key_values::l, R"(.\Data\SKSE\Plugins\resources\key\L_Key_Dark.png)" },
        { key_values::m, R"(.\Data\SKSE\Plugins\resources\key\M_Key_Dark.png)" },
        { key_values::m, R"(.\Data\SKSE\Plugins\resources\key\L_Key_Dark.png)" },
        /*{key_values::comma, R"(.\Data\SKSE\Plugins\resources\key\Mark_Left_Key_Dark.png"},
        {key_values::period, R"(.\Data\SKSE\Plugins\resources\key\Mark_Right_Key_Dark.png"},
        {key_values::backslash, R"(.\Data\SKSE\Plugins\resources\key\Question_Key_Dark.png"},*/
        { key_values::minus, R"(.\Data\SKSE\Plugins\resources\key\Minus_Key_Dark.png)" },
        { key_values::subtract, R"(.\Data\SKSE\Plugins\resources\key\Minus_Key_Dark.png)" },
        { key_values::left_button, R"(.\Data\SKSE\Plugins\resources\key\Mouse_Left_Key_Dark.png)" },
        { key_values::middle_button, R"(.\Data\SKSE\Plugins\resources\key\Mouse_Middle_Key_Dark.png)" },
        { key_values::right_button, R"(.\Data\SKSE\Plugins\resources\key\Mouse_Right_Key_Dark.png)" },
        { key_values::mouse_button_4, R"(.\Data\SKSE\Plugins\resources\key\Mouse_Simple_Key_Dark.png)" },
        { key_values::mouse_button_5, R"(.\Data\SKSE\Plugins\resources\key\Mouse_Simple_Key_Dark.png)" },
        { key_values::mouse_button_6, R"(.\Data\SKSE\Plugins\resources\key\Mouse_Simple_Key_Dark.png)" },
        { key_values::mouse_button_7, R"(.\Data\SKSE\Plugins\resources\key\Mouse_Simple_Key_Dark.png)" },
        { key_values::n, R"(.\Data\SKSE\Plugins\resources\key\N_Key_Dark.png)" },
        { key_values::numlock, R"(.\Data\SKSE\Plugins\resources\key\Num_Lock_Key_Dark.png)" },
        { key_values::o, R"(.\Data\SKSE\Plugins\resources\key\O_Key_Dark.png)" },
        { key_values::p, R"(.\Data\SKSE\Plugins\resources\key\P_Key_Dark.png)" },
        { key_values::next, R"(.\Data\SKSE\Plugins\resources\key\Page_Down_Key_Dark.png)" },
        { key_values::prior, R"(.\Data\SKSE\Plugins\resources\key\Page_Up_Key_Dark.png)" },
        { key_values::add, R"(.\Data\SKSE\Plugins\resources\key\Plus_Key_Dark.png)" },
        { key_values::r, R"(.\Data\SKSE\Plugins\resources\key\R_Key_Dark.png)" },
        { key_values::s, R"(.\Data\SKSE\Plugins\resources\key\S_Key_Dark.png)" },
        { key_values::semicolon, R"(.\Data\SKSE\Plugins\resources\key\Semicolon_Key_Dark.png)" },
        { key_values::lshift, R"(.\Data\SKSE\Plugins\resources\key\Shift_Key_Dark.png)" },
        { key_values::rshift, R"(.\Data\SKSE\Plugins\resources\key\Shift_Key_Dark.png)" },
        //{ key_values::slash, R"(.\Data\SKSE\Plugins\resources\key\Slash_Key_Dark.png)" },
        { key_values::space, R"(.\Data\SKSE\Plugins\resources\key\Space_Key_Dark.png)" },
        { key_values::t, R"(.\Data\SKSE\Plugins\resources\key\T_Key_Dark.png)" },
        { key_values::tab, R"(.\Data\SKSE\Plugins\resources\key\Tab_Key_Dark.png)" },
        { key_values::t, R"(.\Data\SKSE\Plugins\resources\key\Tab_Key_Dark.png)" },
        { key_values::u, R"(.\Data\SKSE\Plugins\resources\key\U_Key_Dark.png)" },
        { key_values::v, R"(.\Data\SKSE\Plugins\resources\key\V_Key_Dark.png)" },
        { key_values::w, R"(.\Data\SKSE\Plugins\resources\key\W_Key_Dark.png)" },
        { key_values::lwin, R"(.\Data\SKSE\Plugins\resources\key\Win_Key_Dark.png)" },
        { key_values::rwin, R"(.\Data\SKSE\Plugins\resources\key\Win_Key_Dark.png)" },
        { key_values::x, R"(.\Data\SKSE\Plugins\resources\key\X_Key_Dark.png)" },
        { key_values::y, R"(.\Data\SKSE\Plugins\resources\key\Y_Key_Dark.png)" },
        { key_values::z, R"(.\Data\SKSE\Plugins\resources\key\Z_Key_Dark.png)" },
    };

    enum class gamepad_values : uint32_t {
        up = 266,
        down,
        left,
        right,
        start,
        back,
        left_thumb,
        right_thumb,
        left_shoulder,
        right_shoulder,
        a,
        b,
        x,
        y,
        left_trigger,
        right_trigger,
        total
    };

    inline static std::map<gamepad_values, const char*> gamepad_ps_icon_path_map = {
        { gamepad_values::up, R"(.\Data\SKSE\Plugins\resources\key\PS5_Dpad_Up.png)" },
        { gamepad_values::down, R"(.\Data\SKSE\Plugins\resources\key\PS5_Dpad_Down.png)" },
        { gamepad_values::left, R"(.\Data\SKSE\Plugins\resources\key\PS5_Dpad_Left.png)" },
        { gamepad_values::right, R"(.\Data\SKSE\Plugins\resources\key\PS5_Dpad_Right.png)" },
        { gamepad_values::start, R"(.\Data\SKSE\Plugins\resources\key\PS5_Options_Alt.png)" },
        { gamepad_values::back, R"(.\Data\SKSE\Plugins\resources\key\PS5_Share_Alt.png)" },
        { gamepad_values::left_thumb, R"(.\Data\SKSE\Plugins\resources\key\PS5_Left_Stick_Click.png)" },
        { gamepad_values::right_thumb, R"(.\Data\SKSE\Plugins\resources\key\PS5_Right_Stick_Click.png)" },
        { gamepad_values::left_shoulder, R"(.\Data\SKSE\Plugins\resources\key\PS5_L1.png)" },
        { gamepad_values::right_shoulder, R"(.\Data\SKSE\Plugins\resources\key\PS5_R1.png)" },
        { gamepad_values::a, R"(.\Data\SKSE\Plugins\resources\key\PS5_Cross.png)" },
        { gamepad_values::b, R"(.\Data\SKSE\Plugins\resources\key\PS5_Circle.png)" },
        { gamepad_values::x, R"(.\Data\SKSE\Plugins\resources\key\PS5_Square.png)" },
        { gamepad_values::y, R"(.\Data\SKSE\Plugins\resources\key\PS5_Triangle.png)" },
        { gamepad_values::left_trigger, R"(.\Data\SKSE\Plugins\resources\key\PS5_L2.png)" },
        { gamepad_values::right_trigger, R"(.\Data\SKSE\Plugins\resources\key\PS5_R2.png)" }
    };

    inline static std::map<gamepad_values, const char*> gamepad_xbox_icon_path_map = {
        { gamepad_values::up, R"(.\Data\SKSE\Plugins\resources\key\XboxSeriesX_Dpad_Up.png)" },
        { gamepad_values::down, R"(.\Data\SKSE\Plugins\resources\key\XboxSeriesX_Dpad_Down.png)" },
        { gamepad_values::left, R"(.\Data\SKSE\Plugins\resources\key\XboxSeriesX_Dpad_Left.png)" },
        { gamepad_values::right, R"(.\Data\SKSE\Plugins\resources\key\XboxSeriesX_Dpad_Right.png)" },
        { gamepad_values::start, R"(.\Data\SKSE\Plugins\resources\key\XboxSeriesX_Menu.png)" },
        { gamepad_values::back, R"(.\Data\SKSE\Plugins\resources\key\XboxSeriesX_View.png)" },
        { gamepad_values::left_thumb, R"(.\Data\SKSE\Plugins\resources\key\XboxSeriesX_Left_Stick_Click.png)" },
        { gamepad_values::right_thumb, R"(.\Data\SKSE\Plugins\resources\key\XboxSeriesX_Right_Stick_Click.png)" },
        { gamepad_values::left_shoulder, R"(.\Data\SKSE\Plugins\resources\key\XboxSeriesX_LB.png)" },
        { gamepad_values::right_shoulder, R"(.\Data\SKSE\Plugins\resources\key\XboxSeriesX_RB.png)" },
        { gamepad_values::a, R"(.\Data\SKSE\Plugins\resources\key\XboxSeriesX_A.png)" },
        { gamepad_values::b, R"(.\Data\SKSE\Plugins\resources\key\XboxSeriesX_B.png)" },
        { gamepad_values::x, R"(.\Data\SKSE\Plugins\resources\key\XboxSeriesX_X.png)" },
        { gamepad_values::y, R"(.\Data\SKSE\Plugins\resources\key\XboxSeriesX_Y.png)" },
        { gamepad_values::left_trigger, R"(.\Data\SKSE\Plugins\resources\key\XboxSeriesX_LT.png)" },
        { gamepad_values::right_trigger, R"(.\Data\SKSE\Plugins\resources\key\XboxSeriesX_RT.png)" }
    };

    enum class controller_set:uint32_t {
        playstation = 0,
        xbox = 1
    };
}
