set(sources ${sources}
	src/PCH.h
	src/equip/equip_slot.cpp
	src/equip/equip_slot.h
	src/event/key_manager.cpp
	src/event/key_manager.h
	src/event/sink_event.cpp
	src/event/sink_event.h
	src/handle/data/data_helper.h
	src/handle/key_position.cpp
	src/handle/key_position.h
	src/handle/page/fade_setting.h
	src/handle/page/hud_offset_setting.h
	src/handle/page/page_setting.h
	src/handle/page/slot_setting.h
	src/handle/page_handle.cpp
	src/handle/page_handle.h
	src/handle/set_data.cpp
	src/handle/set_data.h
	src/handle/setting_execute.cpp
	src/handle/setting_execute.h
	src/item/inventory.cpp
	src/item/inventory.h
	src/item/potion.cpp
	src/item/potion.h
	src/item/weapon.cpp
	src/item/weapon.h
	src/magic/power.cpp
	src/magic/power.h
	src/magic/shout.cpp
	src/magic/shout.h
	src/magic/spell.cpp
	src/magic/spell.h
	src/main.cpp
	src/papyrus/papyrus.cpp
	src/papyrus/papyrus.h
	src/setting/file_setting.cpp
	src/setting/file_setting.h
	src/setting/mcm_setting.cpp
	src/setting/mcm_setting.h
	src/ui/image_path.h
	src/ui/key_path.h
	src/ui/ui_renderer.cpp
	src/ui/ui_renderer.h
	src/util/constant.h
	src/util/offset.h
	src/util/string_util.h
)
