set(sources ${sources}
	src/PCH.h
	src/event/key_manager.cpp
	src/event/key_manager.h
	src/event/sink_event.cpp
	src/event/sink_event.h
	src/handle/read_data.cpp
	src/handle/read_data.h
	src/handle/slot_setting_handle.cpp
	src/handle/slot_setting_handle.h
	src/item/inventory.cpp
	src/item/inventory.h
	src/item/potion.cpp
	src/item/potion.h
	src/item/weapon.cpp
	src/item/weapon.h
	src/magic/power.cpp
	src/magic/power.h
	src/magic/shout.cpp
	src/magic/shout.h
	src/magic/spell.cpp
	src/magic/spell.h
	src/main.cpp
	src/papyrus/papyrus.cpp
	src/papyrus/papyrus.h
	src/setting/file_setting.cpp
	src/setting/file_setting.h
	src/setting/mcm_setting.cpp
	src/setting/mcm_setting.h
	src/ui/hud.cpp
	src/ui/hud.h
	src/util/constant.h
	src/util/string_util.h
)
