set(sources ${sources}
	src/PCH.h
	src/equip/equip_slot.cpp
	src/equip/equip_slot.h
	src/equip/item.cpp
	src/equip/item.h
	src/equip/magic.cpp
	src/equip/magic.h
	src/event/equip_event.cpp
	src/event/equip_event.h
	src/event/key_manager.cpp
	src/event/key_manager.h
	src/event/sink_event.cpp
	src/event/sink_event.h
	src/handle/data/data_helper.h
	src/handle/data/page/position_draw_setting.h
	src/handle/data/page/position_setting.h
	src/handle/data/page/slot_setting.h
	src/handle/handle/edit_handle.cpp
	src/handle/handle/edit_handle.h
	src/handle/handle/key_position_handle.cpp
	src/handle/handle/key_position_handle.h
	src/handle/handle/name_handle.cpp
	src/handle/handle/name_handle.h
	src/handle/handle/page_handle.cpp
	src/handle/handle/page_handle.h
	src/handle/setting/set_setting_data.cpp
	src/handle/setting/set_setting_data.h
	src/handle/setting/setting_execute.cpp
	src/handle/setting/setting_execute.h
	src/hook/hook.cpp
	src/hook/hook.h
	src/main.cpp
	src/papyrus/papyrus.cpp
	src/papyrus/papyrus.h
	src/setting/custom_setting.cpp
	src/setting/custom_setting.h
	src/setting/file_setting.cpp
	src/setting/file_setting.h
	src/setting/mcm_setting.cpp
	src/setting/mcm_setting.h
	src/ui/image_path.h
	src/ui/key_path.h
	src/ui/ui_renderer.cpp
	src/ui/ui_renderer.h
	src/util/constant.h
	src/util/helper.cpp
	src/util/helper.h
	src/util/offset.h
	src/util/string_util.h
)
